name: auto-approve
on: pull_request

permissions:
  pull-requests: write

jobs:
  approve_pr:
    name: Approve Bot PRs
    runs-on: ubuntu-latest
    # Scala Steward runs with td-scala-steward user
    if: ${{ github.actor == 'td-scala-steward' || github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve the pull request
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          # Set a token for approving the PR on behalf of the repo owner
          GITHUB_TOKEN: ${{ secrets.TD_ACTIONS_REPO_TOKEN }}
