name: Release

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  release:
    name: Create a new release
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TD_ACTIONS_REPO_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        # We need to fetch all tags to get the latest tag
        with:
         fetch-depth: 0
      - if: startsWith(github.ref, 'refs/tags/v')
        name: Create a release note
        run: |
          gh release view "$GITHUB_REF_NAME" --repo="$GITHUB_REPOSITORY" | \
          # Create a new release note only when the release note is not created yet
          gh release create "$GITHUB_REF_NAME" --repo="$GITHUB_REPOSITORY" --generate-notes
