name: SDKs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  python:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: unittest
        run: python -m unittest
        working-directory: sdks/python
